#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [ "$CURRENT_BRANCH" = "main" ]; then
  echo "You can't commit to main!"
  exit 1
fi
npm run build
npm run docs
npx lint-staged
