name: Build, Test, and Publish to NPM Registry
on:
  push:
    branches: [main]
jobs:
  publish:
    name: 'On Main Push - Release version to NPM Registry'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup configuration for NPM registry
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.0'
          registry-url: 'https://registry.npmjs.org'
          scope: '@dankreiger'

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      # - name: Test
      #   run: npm run test --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build

      - name: Create release and publish scoped package
        run: HUSKY=0 yarn semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish unscoped package
        run: |
          sed -ie 's/@dankreiger\///g' package.json
          npm publish
          mv package.jsone package.json
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
