name: NPM Audit

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-
      - name: Install Dependencies
        run: yarn
      - name: Run a security audit
        run: npx audit-ci --critical --report-type summary
