name: Pull Request
on: [pull_request]
jobs:
  pull_request:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v3
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:ci
      - name: Build
        run: npm run build
      - name: size-limit-action
        uses: andresz1/size-limit-action@v1.7.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
