name: Pull Request
on: [pull_request]
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: npm run lint
      # - name: Test
      #   run: npm run test --ci --coverage --maxWorkers=2
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
